create table if not exists public.toybox_runs (
  id uuid primary key default gen_random_uuid(),
  game text not null check (game in ('harmony','drawing','secret')),
  status text not null default 'active' check (status in ('invited','active','completed','abandoned')),
  initiator text not null default 'user' check (initiator in ('user','luze')),
  chat_session_id text,
  title text,
  state jsonb not null default '{}'::jsonb,
  result jsonb not null default '{}'::jsonb,
  model text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz
);

create table if not exists public.toybox_events (
  id bigint generated by default as identity primary key,
  run_id uuid not null references public.toybox_runs(id) on delete cascade,
  actor text not null check (actor in ('user','luze','system')),
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists toybox_runs_updated_idx on public.toybox_runs(updated_at desc);
create index if not exists toybox_runs_status_idx on public.toybox_runs(status, updated_at desc);
create index if not exists toybox_events_run_idx on public.toybox_events(run_id, created_at asc);

alter table public.toybox_runs enable row level security;
alter table public.toybox_events enable row level security;
revoke all on table public.toybox_runs from anon, authenticated;
revoke all on table public.toybox_events from anon, authenticated;
revoke all on sequence public.toybox_events_id_seq from anon, authenticated;
grant select, insert, update, delete on table public.toybox_runs to service_role;
grant select, insert, update, delete on table public.toybox_events to service_role;
grant usage, select on sequence public.toybox_events_id_seq to service_role;
