-- OurHome layered memory foundation.
-- Existing rows are preserved: protected memories become core, the rest start as episodic.
-- Temporary working memory continues to live in memory_marks and expires into history instead of being deleted.

alter table public.memories
  add column if not exists memory_tier text not null default 'episodic',
  add column if not exists memory_kind text not null default 'general',
  add column if not exists confidence numeric(4,3) not null default 0.750,
  add column if not exists source_type text,
  add column if not exists source_id text,
  add column if not exists expires_at timestamptz,
  add column if not exists reinforcement_count integer not null default 0,
  add column if not exists superseded_by bigint references public.memories(id) on delete set null,
  add column if not exists last_confirmed_at timestamptz,
  add column if not exists archived_at timestamptz;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'memories_memory_tier_check'
  ) then
    alter table public.memories
      add constraint memories_memory_tier_check
      check (memory_tier in ('temporary', 'episodic', 'core', 'archived'));
  end if;
  if not exists (
    select 1 from pg_constraint where conname = 'memories_confidence_check'
  ) then
    alter table public.memories
      add constraint memories_confidence_check
      check (confidence >= 0 and confidence <= 1);
  end if;
  if not exists (
    select 1 from pg_constraint where conname = 'memories_reinforcement_count_check'
  ) then
    alter table public.memories
      add constraint memories_reinforcement_count_check
      check (reinforcement_count >= 0);
  end if;
end $$;

create or replace function public.ourhome_classify_memory_kind(value text)
returns text
language sql
immutable
as $$
  select case
    when coalesce(value, '') ~* '(姓名|昵称|身份|生日|年龄|身高|学校|专业|职业|毕业|家乡)' then 'identity'
    when coalesce(value, '') ~* '(喜欢|偏好|讨厌|不喜欢|口味|风格|习惯|常用|最爱)' then 'preference'
    when coalesce(value, '') ~* '(禁止|边界|不允许|不要说|不要用|不能接受|必须避免)' then 'boundary'
    when coalesce(value, '') ~* '(伴侣|夫妻|结婚|纪念日|戒指|称呼|我们的关系|约定)' then 'relationship'
    when coalesce(value, '') ~* '(计划|准备|打算|待办|明天|以后|部署|上线|要做)' then 'plan'
    when coalesce(value, '') ~* '(今天|现在|刚刚|正在|暂时|最近|这几天)' then 'state'
    when coalesce(value, '') ~* '(生病|发烧|疼|痛|月经|医院|药|睡眠|身体)' then 'health'
    when coalesce(value, '') ~* '(项目|OurHome|论文|工作|面试|课程|小剧场|共读)' then 'project'
    else 'event'
  end;
$$;

update public.memories
set memory_tier = case when coalesce(is_protected, false) then 'core' else 'episodic' end,
    memory_kind = public.ourhome_classify_memory_kind(summary),
    confidence = case when coalesce(is_protected, false) then 0.950 else greatest(confidence, 0.750) end,
    source_type = coalesce(source_type, nullif(metadata ->> 'source_type', ''), 'legacy'),
    last_confirmed_at = coalesce(last_confirmed_at, timestamp, now())
where true;

alter table public.memory_marks
  add column if not exists expires_at timestamptz,
  add column if not exists reinforcement_count integer not null default 0,
  add column if not exists superseded_by uuid references public.memory_marks(id) on delete set null,
  add column if not exists settled_at timestamptz;

update public.memory_marks
set expires_at = coalesce(
  expires_at,
  created_at + case
    when coalesce(importance, 1) >= 4 then interval '90 days'
    when coalesce(should_remember, false) then interval '45 days'
    when coalesce(should_continue, false) then interval '30 days'
    else interval '14 days'
  end
)
where expires_at is null;

create table if not exists public.memory_consolidations (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  expired_working_count integer not null default 0,
  archived_temporary_count integer not null default 0,
  promoted_episodic_count integer not null default 0,
  promoted_core_count integer not null default 0,
  deduplicated_count integer not null default 0,
  details jsonb not null default '{}'::jsonb
);

create or replace function public.ourhome_prepare_memory_row()
returns trigger
language plpgsql
as $$
begin
  if new.memory_tier is null or new.memory_tier not in ('temporary', 'episodic', 'core', 'archived') then
    new.memory_tier := case when coalesce(new.is_protected, false) then 'core' else 'episodic' end;
  end if;

  if tg_op = 'INSERT'
     or new.summary is distinct from old.summary
     or new.memory_kind is null
     or new.memory_kind = 'general' then
    new.memory_kind := public.ourhome_classify_memory_kind(new.summary);
  end if;

  new.confidence := greatest(0, least(1, coalesce(new.confidence, 0.750)));
  new.reinforcement_count := greatest(0, coalesce(new.reinforcement_count, 0));
  new.source_type := coalesce(new.source_type, nullif(new.metadata ->> 'source_type', ''), 'chat');

  if coalesce(new.is_protected, false) then
    new.memory_tier := 'core';
  end if;

  if new.memory_tier = 'core' then
    new.is_protected := true;
    new.expires_at := null;
    new.last_confirmed_at := coalesce(new.last_confirmed_at, now());
  elsif new.memory_tier = 'archived' then
    new.is_protected := false;
    new.archived_at := coalesce(new.archived_at, now());
  else
    new.is_protected := false;
    new.archived_at := null;
  end if;

  if tg_op = 'UPDATE'
     and new.last_referenced_at is distinct from old.last_referenced_at
     and new.last_referenced_at is not null then
    new.reinforcement_count := greatest(0, coalesce(old.reinforcement_count, 0)) + 1;
  end if;

  return new;
end;
$$;

drop trigger if exists memories_prepare_layered_row on public.memories;
create trigger memories_prepare_layered_row
before insert or update on public.memories
for each row execute function public.ourhome_prepare_memory_row();

create or replace function public.ourhome_prepare_memory_mark()
returns trigger
language plpgsql
as $$
begin
  new.reinforcement_count := greatest(0, coalesce(new.reinforcement_count, 0));
  if new.expires_at is null then
    new.expires_at := coalesce(new.created_at, now()) + case
      when coalesce(new.importance, 1) >= 4 then interval '90 days'
      when coalesce(new.should_remember, false) then interval '45 days'
      when coalesce(new.should_continue, false) then interval '30 days'
      else interval '14 days'
    end;
  end if;
  return new;
end;
$$;

drop trigger if exists memory_marks_prepare_layered_row on public.memory_marks;
create trigger memory_marks_prepare_layered_row
before insert or update on public.memory_marks
for each row execute function public.ourhome_prepare_memory_mark();

create or replace function public.ourhome_consolidate_memory_layers()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  expired_working integer := 0;
  archived_temporary integer := 0;
  promoted_episodic integer := 0;
  promoted_core integer := 0;
  deduplicated integer := 0;
  result jsonb;
begin
  update public.memory_marks
  set status = 'expired',
      settled_at = coalesce(settled_at, now())
  where status in ('active', 'continued')
    and expires_at is not null
    and expires_at <= now();
  get diagnostics expired_working = row_count;

  update public.memories
  set memory_tier = 'archived',
      archived_at = coalesce(archived_at, now())
  where memory_tier = 'temporary'
    and expires_at is not null
    and expires_at <= now();
  get diagnostics archived_temporary = row_count;

  update public.memories
  set memory_tier = 'episodic',
      expires_at = null,
      last_confirmed_at = coalesce(last_confirmed_at, now())
  where memory_tier = 'temporary'
    and (reinforcement_count >= 3 or coalesce(weight, 1) >= 1.5)
    and (expires_at is null or expires_at > now());
  get diagnostics promoted_episodic = row_count;

  update public.memories
  set memory_tier = 'core',
      is_protected = true,
      confidence = greatest(confidence, 0.900),
      expires_at = null,
      last_confirmed_at = coalesce(last_confirmed_at, now())
  where memory_tier = 'episodic'
    and memory_kind in ('identity', 'preference', 'boundary', 'relationship')
    and (reinforcement_count >= 2 or coalesce(weight, 1) >= 1.8);
  get diagnostics promoted_core = row_count;

  with ranked as (
    select
      id,
      first_value(id) over (
        partition by regexp_replace(lower(trim(summary)), '[[:space:][:punct:]]+', '', 'g')
        order by coalesce(is_protected, false) desc, coalesce(weight, 1) desc, timestamp asc nulls last, id asc
      ) as keeper_id,
      row_number() over (
        partition by regexp_replace(lower(trim(summary)), '[[:space:][:punct:]]+', '', 'g')
        order by coalesce(is_protected, false) desc, coalesce(weight, 1) desc, timestamp asc nulls last, id asc
      ) as duplicate_rank
    from public.memories
    where memory_tier <> 'archived'
      and nullif(trim(summary), '') is not null
  ), duplicates as (
    select id, keeper_id
    from ranked
    where duplicate_rank > 1 and id <> keeper_id
  )
  update public.memories memory
  set memory_tier = 'archived',
      is_protected = false,
      superseded_by = duplicates.keeper_id,
      archived_at = coalesce(memory.archived_at, now())
  from duplicates
  where memory.id = duplicates.id
    and not coalesce(memory.is_protected, false);
  get diagnostics deduplicated = row_count;

  result := jsonb_build_object(
    'expired_working_count', expired_working,
    'archived_temporary_count', archived_temporary,
    'promoted_episodic_count', promoted_episodic,
    'promoted_core_count', promoted_core,
    'deduplicated_count', deduplicated,
    'ran_at', now()
  );

  insert into public.memory_consolidations (
    expired_working_count,
    archived_temporary_count,
    promoted_episodic_count,
    promoted_core_count,
    deduplicated_count,
    details
  ) values (
    expired_working,
    archived_temporary,
    promoted_episodic,
    promoted_core,
    deduplicated,
    result
  );

  return result;
end;
$$;

create index if not exists memories_tier_weight_idx
  on public.memories(memory_tier, weight desc, timestamp desc);
create index if not exists memories_expires_at_idx
  on public.memories(expires_at) where expires_at is not null;
create index if not exists memories_superseded_by_idx
  on public.memories(superseded_by) where superseded_by is not null;
create index if not exists memory_marks_expires_at_idx
  on public.memory_marks(expires_at) where expires_at is not null;
create index if not exists memory_marks_superseded_by_idx
  on public.memory_marks(superseded_by) where superseded_by is not null;

create or replace view public.memory_core as
select *
from public.memories
where memory_tier = 'core';

create or replace view public.memory_episodic as
select *
from public.memories
where memory_tier = 'episodic';

create or replace view public.memory_working as
select *
from public.memory_marks
where status in ('active', 'continued')
  and (expires_at is null or expires_at > now());

create or replace view public.memory_layer_stats as
select
  (select count(*) from public.memories where memory_tier = 'core') as core_count,
  (select count(*) from public.memories where memory_tier = 'episodic') as episodic_count,
  (select count(*) from public.memories where memory_tier = 'temporary') as temporary_record_count,
  (select count(*) from public.memories where memory_tier = 'archived') as archived_count,
  (select count(*) from public.memory_marks where status in ('active', 'continued') and (expires_at is null or expires_at > now())) as working_count;

revoke all on public.memory_consolidations from public, anon, authenticated;
revoke all on public.memory_core from public, anon, authenticated;
revoke all on public.memory_episodic from public, anon, authenticated;
revoke all on public.memory_working from public, anon, authenticated;
revoke all on public.memory_layer_stats from public, anon, authenticated;
revoke all on function public.ourhome_consolidate_memory_layers() from public, anon, authenticated;

grant all on public.memory_consolidations to service_role;
grant select on public.memory_core, public.memory_episodic, public.memory_working, public.memory_layer_stats to service_role;
grant execute on function public.ourhome_consolidate_memory_layers() to service_role;

select public.ourhome_consolidate_memory_layers();
